"""Gera data/medicamentos.json a partir do formulário do ICAM.

Este script é a fonte editável dos dados: para adicionar/corrigir um
medicamento, altere a lista MEDICAMENTOS abaixo e rode:

    python3 scripts/gerar_dados.py

Ele regrava data/medicamentos.json. O arquivo data/interacoes.json é
mantido/editado manualmente (não é gerado por este script).

IMPORTANTE: os valores de dose (mg/kg) foram preenchidos com base em
literatura pediátrica padrão (equivalente ao formato de fichas técnicas
como as do Guia Farmacêutico do Hospital Sírio-Libanês) sempre que havia
uma referência de mg/kg amplamente aceita. Quando o item não possui uma
dose pediátrica padronizada em mg/kg (ex.: tópicos, contrastes, gases
anestésicos, insumos), os campos de dose ficam como None e o item aparece
no sistema como "sem referência cadastrada" — ainda assim disponível para
cálculo de frascos/dose unitária. TODOS os valores devem ser validados
pela farmácia clínica do ICAM antes do uso em produção.
"""
import json
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"


def ap(forma, concentracao, unidade, volume_frasco_mL=None):
    d = {"forma": forma, "concentracao": concentracao, "unidade": unidade}
    if volume_frasco_mL is not None:
        d["volume_frasco_mL"] = volume_frasco_mL
    return d


def m(id, nome, classe, categoria, vias, apresentacoes,
      dose_min=None, dose_max=None, int_min=None, int_max=None,
      max_dia_kg=None, max_abs=None, obs=""):
    return {
        "id": id,
        "nome": nome,
        "classe": classe,
        "categoria": categoria,
        "vias": vias,
        "apresentacoes": apresentacoes,
        "dose_min_mg_kg_dose": dose_min,
        "dose_max_mg_kg_dose": dose_max,
        "intervalo_horas_min": int_min,
        "intervalo_horas_max": int_max,
        "dose_max_dia_mg_kg": max_dia_kg,
        "dose_max_absoluta_mg_dia": max_abs,
        "observacoes": obs,
    }


INJ = "Injetáveis"
COMP = "Comprimidos e Cápsulas"
SUSP = "Suspensões e Soluções Orais"
GTS = "Gotas e Emulsão"
XPE = "Xaropes e Elixir"
TOP = "Pomadas, Cremes e Loções"
INAL = "Inalatórios"
OFT = "Oftálmicos"
ELET = "Eletrólitos"
CONT = "Contrastes"
TERM = "Termolábeis"
RESERVA = "Antimicrobianos de Reserva"
CTRL_INJ = "Controlados Injetáveis"
CTRL_ANEST = "Controlados Anestésicos"
CTRL_ORAL_GTS = "Controlados Orais e Gotas"
CTRL_COMP = "Controlados Comprimidos"

# ---------------------------------------------------------------------------
# Classificação regulatória/operacional (painel "Medicamentos do Hospital")
# ---------------------------------------------------------------------------
# As categorias abaixo, usadas para derivar boa parte desses campos, refletem
# a própria divisão do formulário do ICAM (que já separa "Controlados" dos
# demais itens). Os campos derivados aqui são um ponto de partida — a
# classificação legal (Portaria SVS/MS 344/98) e as listas de uso coletivo
# DEVEM ser conferidas e mantidas pelo farmacêutico responsável do ICAM.

# Categorias que o próprio ICAM já trata como "Controlados" no formulário
# (sujeitas a controle especial de dispensação/guarda).
CATEGORIAS_CONTROLADAS = {CTRL_INJ, CTRL_ANEST, CTRL_ORAL_GTS, CTRL_COMP}

# Categorias em que o conceito de "dose unitária" (cálculo de fração de
# frasco/ampola/frasco por dose) não se aplica — uso tópico/local, sem
# posologia sistêmica por peso.
SEM_DOSE_UNITARIA_CATEGORIAS = {TOP, OFT, CONT}

# Medicamentos efetivamente listados na Portaria SVS/MS n° 344/98 (controle
# especial), com a respectiva lista/anexo. Mapeamento por conhecimento
# farmacológico geral — CONFIRMAR com a farmácia/RT antes de uso oficial,
# especialmente os marcados "verificar" (classificação com atualizações
# recentes da ANVISA).
PORTARIA_344 = {
    # Lista A1 — entorpecentes
    "morfina": "A1",
    "fentanil": "A1",
    "metadona": "A1",
    "remifentanila": "A1",
    "tramadol": "A1 (verificar atualização ANVISA)",
    # Controle especial de abuso — classificação sujeita a confirmação
    "escetamina": "Controle especial (verificar lista atualizada)",
    # Lista B1 — psicotrópicos (benzodiazepínicos e barbitúricos)
    "midazolam": "B1",
    "diazepam_inj": "B1",
    "diazepam_comp": "B1",
    "clonazepam_gts": "B1",
    "clonazepam_comp": "B1",
    "lorazepam": "B1",
    "clobazam": "B1",
    "fenobarbital_inj": "B1",
    "fenobarbital_susp": "B1",
    "fenobarbital_comp": "B1",
    "tiopental": "B1",
    # Lista C1 — outras substâncias sujeitas a controle especial
    "haloperidol_inj": "C1",
    "haloperidol_comp": "C1",
    "haloperidol_gts": "C1",
    "haloperidol_decanoato": "C1",
    "clorpromazina": "C1",
    "risperidona": "C1",
    "fenitoina": "C1",
    "carbamazepina_comp": "C1",
    "carbamazepina_susp": "C1",
    "valproato_xarope": "C1",
    "topiramato": "C1",
    "lamotrigina": "C1",
    "levetiracetam_comp": "C1",
    "levetiracetam_susp": "C1",
    "fluoxetina": "C1",
}

# Medicamentos de "uso coletivo" (mantidos como estoque comum/de posto,
# não individualizados por paciente) — diluentes, soluções e eletrólitos de
# uso corrente. Lista de partida; a relação oficial de uso coletivo do ICAM
# deve ser validada pela CFT/farmácia.
USO_COLETIVO_IDS = {
    "agua_destilada",
    "cloreto_sodio_10",
    "cloreto_sodio_inal",
    "glicose_50",
    "gliconato_calcio",
    "sulfato_magnesio",
    "manitol",
    "oleo_mineral",
    "creme_barreira",
    "oxido_zinco_pasta",
}


def classificar(med):
    """Preenche os campos de classificação operacional/regulatória usados no
    painel "Medicamentos do Hospital": disponibilidade, uso controlado,
    lista da Portaria 344, necessidade de dose unitária, necessidade de o
    farmacêutico definir a quantidade de frascos/ampolas liberada, e uso
    coletivo vs. individualizado.
    """
    categoria = med["categoria"]
    apresentacoes = med["apresentacoes"]

    lista_344 = PORTARIA_344.get(med["id"])
    portaria_344 = lista_344 is not None

    requer_dose_unitaria = categoria not in SEM_DOSE_UNITARIA_CATEGORIAS and any(
        not ap["unidade"].endswith("/comprimido") for ap in apresentacoes
    )

    med["disponivel"] = True
    med["uso_controlado"] = categoria in CATEGORIAS_CONTROLADAS
    med["portaria_344"] = portaria_344
    med["portaria_344_lista"] = lista_344
    med["requer_dose_unitaria"] = requer_dose_unitaria
    med["farmaceutico_define_frascos"] = portaria_344 and requer_dose_unitaria
    med["uso_coletivo"] = categoria == ELET or med["id"] in USO_COLETIVO_IDS
    return med

MEDICAMENTOS = [
    # ------------------------------------------------------------ INJETÁVEIS
    m("acetilcisteina", "Acetilcisteína", "Mucolítico / Antídoto (paracetamol)", INJ,
      ["EV"], [ap("Ampola 3 mL", 100, "mg/mL")],
      dose_min=150, dose_max=150, int_min=4, int_max=16,
      obs="Protocolo de intoxicação por paracetamol: 150 mg/kg (ataque), depois infusões escalonadas. Diluir em SG5%."),
    m("acido_ascorbico_inj", "Ácido Ascórbico (Vitamina C) injetável", "Vitamina", INJ,
      ["EV", "IM"], [ap("Ampola 5 mL", 100, "mg/mL")],
      dose_min=1, dose_max=3, int_min=12, int_max=24, max_abs=500,
      obs="Reposição/escorbuto. Dose ampla conforme indicação clínica."),
    m("acido_tranexamico", "Ácido Tranexâmico", "Antifibrinolítico", INJ,
      ["EV"], [ap("Ampola 5 mL", 50, "mg/mL")],
      dose_min=10, dose_max=15, int_min=8, int_max=8, max_abs=1000,
      obs="Infundir lentamente (risco de hipotensão em bolus rápido)."),
    m("aciclovir", "Aciclovir", "Antiviral", INJ,
      ["EV"], [ap("Frasco-ampola (pó p/ diluição)", 250, "mg/frasco")],
      dose_min=10, dose_max=20, int_min=8, int_max=8, max_abs=1500,
      obs="Infundir em no mínimo 1h. Hidratar bem (risco de nefrotoxicidade)."),
    m("albumina_humana", "Albumina Humana 20%", "Expansor plasmático / Hemoderivado", INJ,
      ["EV"], [ap("Frasco-ampola 50 mL (20%)", 200, "mg/mL")],
      dose_min=0.5, dose_max=1, int_min=24, int_max=24, max_abs=None,
      obs="Dose expressa em g/kg (0,5-1 g/kg); infundir conforme protocolo, monitorar volemia."),
    m("amicacina", "Amicacina", "Antibiótico (Aminoglicosídeo)", INJ,
      ["EV", "IM"], [ap("Ampola 2 mL", 250, "mg/mL")],
      dose_min=15, dose_max=22.5, int_min=24, int_max=24, max_dia_kg=22.5,
      obs="Nefro/ototóxico. Monitorar função renal e níveis séricos."),
    m("ampicilina", "Ampicilina", "Antibiótico (Penicilina)", INJ,
      ["EV", "IM"], [ap("Frasco-ampola 500 mg", 500, "mg/frasco"), ap("Frasco-ampola 1 g", 1000, "mg/frasco")],
      dose_min=100, dose_max=200, int_min=6, int_max=8, max_dia_kg=400, max_abs=12000,
      obs="Dose maior (até 400mg/kg/dia) para meningite."),
    m("atropina", "Atropina", "Anticolinérgico / Antídoto", INJ,
      ["EV", "IM", "SC"], [ap("Ampola 1 mL", 0.25, "mg/mL")],
      dose_min=0.02, dose_max=0.02, int_min=4, int_max=6, max_abs=1,
      obs="Dose mínima 0,1mg por administração (risco de bradicardia paradoxal em doses menores)."),
    m("benzilpenicilina_cristalina", "Benzilpenicilina Potássica (Cristalina)", "Antibiótico (Penicilina)", INJ,
      ["EV", "IM"], [ap("Frasco-ampola 5.000.000 UI", 5000000, "UI/frasco")],
      dose_min=100000, dose_max=250000, int_min=4, int_max=6, max_dia_kg=250000, max_abs=24000000,
      obs="Dose expressa em UI/kg/dia."),
    m("benzilpenicilina_benzatina", "Benzilpenicilina Benzatina", "Antibiótico (Penicilina)", INJ,
      ["IM"], [ap("Frasco-ampola 600.000 UI", 600000, "UI/frasco"), ap("Frasco-ampola 1.200.000 UI", 1200000, "UI/frasco")],
      dose_min=25000, dose_max=50000, int_min=None, int_max=None, max_abs=1200000,
      obs="Dose única (profilaxia de febre reumática/sífilis) — não é dose fracionada por dia."),
    m("bromoprida_inj", "Bromoprida injetável", "Antiemético / Procinético", INJ,
      ["EV", "IM"], [ap("Ampola 2 mL", 5, "mg/mL")],
      dose_min=0.5, dose_max=1, int_min=8, int_max=8, max_dia_kg=3,
      obs="Evitar em < 1 ano; risco de reações extrapiramidais."),
    m("bupivacaina", "Bupivacaína 0,5% sem vasoconstritor", "Anestésico local", INJ,
      ["Infiltração", "Bloqueio", "Raqui/Peridural"], [ap("Frasco-ampola", 5, "mg/mL")],
      dose_min=1, dose_max=2, int_min=None, int_max=None, max_abs=None,
      obs="Uso restrito à anestesia/analgesia locorregional; dose depende da técnica."),
    m("bupivacaina_pesada", "Bupivacaína Pesada (com glicose)", "Anestésico local (raquianestesia)", INJ,
      ["Raquianestesia"], [ap("Ampola", 5, "mg/mL")],
      obs="Uso exclusivo em raquianestesia por anestesiologista; sem faixa mg/kg padronizada."),
    m("cefalotina", "Cefalotina Sódica", "Antibiótico (Cefalosporina 1ª geração)", INJ,
      ["EV", "IM"], [ap("Frasco-ampola 1 g", 1000, "mg/frasco")],
      dose_min=80, dose_max=160, int_min=6, int_max=6, max_abs=12000),
    m("cefazolina", "Cefazolina Sódica", "Antibiótico (Cefalosporina 1ª geração)", INJ,
      ["EV", "IM"], [ap("Frasco-ampola 1 g", 1000, "mg/frasco")],
      dose_min=50, dose_max=100, int_min=8, int_max=8, max_dia_kg=100, max_abs=6000,
      obs="Profilaxia cirúrgica: dose única 25-30mg/kg."),
    m("ceftriaxona", "Ceftriaxona", "Antibiótico (Cefalosporina 3ª geração)", INJ,
      ["EV", "IM"], [ap("Frasco-ampola 1 g", 1000, "mg/frasco")],
      dose_min=50, dose_max=100, int_min=12, int_max=24, max_dia_kg=100, max_abs=4000,
      obs="Não administrar com soluções contendo cálcio (risco em neonatos)."),
    m("ciprofloxacino_inj", "Ciprofloxacino injetável", "Antibiótico (Quinolona)", INJ,
      ["EV"], [ap("Bolsa 100 mL", 2, "mg/mL")],
      dose_min=10, dose_max=15, int_min=8, int_max=12, max_abs=800,
      obs="Uso restrito; risco de artropatia (avaliar risco-benefício em pediatria)."),
    m("claritromicina_inj", "Claritromicina injetável", "Antibiótico (Macrolídeo)", INJ,
      ["EV"], [ap("Frasco-ampola (pó p/ diluição)", 500, "mg/frasco")],
      dose_min=15, dose_max=15, int_min=12, int_max=12, max_abs=1000,
      obs="Pode prolongar intervalo QT."),
    m("clindamicina", "Clindamicina", "Antibiótico (Lincosamida)", INJ,
      ["EV", "IM"], [ap("Ampola 4 mL", 150, "mg/mL")],
      dose_min=20, dose_max=40, int_min=6, int_max=8, max_abs=4800,
      obs="Risco de colite associada a Clostridioides difficile."),
    m("dexametasona_inj", "Dexametasona injetável", "Corticosteroide", INJ,
      ["EV", "IM"], [ap("Ampola 2,5 mL", 4, "mg/mL")],
      dose_min=0.15, dose_max=0.6, int_min=6, int_max=12, max_abs=16,
      obs="Uso comum em laringite/crupe (dose única 0,15-0,6 mg/kg)."),
    m("dipirona_inj", "Dipirona Sódica injetável", "Analgésico / Antipirético", INJ,
      ["EV", "IM"], [ap("Ampola 2 mL", 500, "mg/mL")],
      dose_min=10, dose_max=25, int_min=6, int_max=6, max_dia_kg=100, max_abs=4000,
      obs="Evitar em < 3 meses. Risco raro de agranulocitose."),
    m("dobutamina", "Dobutamina", "Inotrópico (agonista beta-1)", INJ,
      ["EV (infusão contínua)"], [ap("Ampola 20 mL", 12.5, "mg/mL")],
      dose_min=2, dose_max=20, int_min=1, int_max=1,
      obs="Dose em mcg/kg/min (2-20). Aqui os campos mg/kg/dose representam mcg/kg/min para fins de cálculo de infusão contínua."),
    m("dopamina", "Dopamina", "Inotrópico / Vasopressor", INJ,
      ["EV (infusão contínua)"], [ap("Ampola 10 mL", 5, "mg/mL")],
      dose_min=2, dose_max=20, int_min=1, int_max=1,
      obs="Dose em mcg/kg/min (2-20, titulável). Usar via exclusiva e bomba de infusão."),
    m("enoxaparina", "Enoxaparina Sódica", "Anticoagulante (HBPM)", INJ,
      ["SC"], [ap("Seringa 20 mg/0,2 mL", 100, "mg/mL"), ap("Seringa 40 mg/0,4 mL", 100, "mg/mL")],
      dose_min=0.5, dose_max=1.5, int_min=12, int_max=24, max_abs=None,
      obs="Dose terapêutica 1mg/kg 12/12h; profilática 0,5mg/kg/dia. Ajustar por função renal."),
    m("epinefrina", "Epinefrina (Adrenalina)", "Vasopressor / Broncodilatador", INJ,
      ["EV", "IM", "IO", "Nebulização"], [ap("Ampola 1 mL", 1, "mg/mL")],
      dose_min=0.01, dose_max=0.01, int_min=3, int_max=5, max_abs=1,
      obs="PCR: 0,01 mg/kg EV/IO (1:10.000) a cada 3-5 min. Anafilaxia IM: 0,01mg/kg (máx. 0,5mg)."),
    m("escopolamina", "Escopolamina (Butilbrometo/Hioscina)", "Antiespasmódico", INJ,
      ["EV", "IM"], [ap("Ampola 1 mL", 20, "mg/mL")],
      dose_min=0.3, dose_max=0.6, int_min=6, int_max=8, max_abs=40),
    m("fitomenadiona", "Fitomenadiona (Vitamina K1)", "Vitamina / Antídoto", INJ,
      ["EV lento", "IM"], [ap("Ampola 1 mL", 10, "mg/mL")],
      dose_min=0.3, dose_max=0.5, int_min=None, int_max=None, max_abs=10,
      obs="Neonatos: 1mg IM dose única (profilaxia doença hemorrágica). Reversão de varfarina: 0,3mg/kg."),
    m("fluconazol_inj", "Fluconazol injetável", "Antifúngico", INJ,
      ["EV"], [ap("Bolsa 100 mL", 2, "mg/mL")],
      dose_min=6, dose_max=12, int_min=24, int_max=24, max_abs=800),
    m("folinato_calcio", "Folinato de Cálcio (Ácido Folínico)", "Antídoto (metotrexato) / Suplemento", INJ,
      ["EV", "IM", "VO"], [ap("Frasco-ampola", 50, "mg/frasco")],
      dose_min=10, dose_max=15, int_min=6, int_max=6, max_abs=None,
      obs="Dose de resgate depende do protocolo de quimioterapia (metotrexato)."),
    m("furosemida", "Furosemida", "Diurético de alça", INJ,
      ["EV", "IM"], [ap("Ampola 2 mL", 10, "mg/mL")],
      dose_min=0.5, dose_max=2, int_min=6, int_max=12, max_dia_kg=6, max_abs=200,
      obs="Potencializa ototoxicidade de aminoglicosídeos e risco de hipocalemia."),
    m("gentamicina", "Gentamicina", "Antibiótico (Aminoglicosídeo)", INJ,
      ["EV", "IM"], [ap("Ampola 1 mL", 40, "mg/mL"), ap("Ampola 2 mL", 40, "mg/mL")],
      dose_min=5, dose_max=7.5, int_min=24, int_max=24, max_dia_kg=7.5, max_abs=400,
      obs="Nefro/ototóxico. Monitorar função renal; evitar com outros nefrotóxicos."),
    m("heparina_sodica", "Heparina Sódica", "Anticoagulante", INJ,
      ["EV", "SC"], [ap("Frasco-ampola 5 mL", 5000, "UI/mL")],
      dose_min=75, dose_max=100, int_min=None, int_max=None, max_abs=None,
      obs="Dose de ataque 75-100 UI/kg (bolus), manutenção por infusão contínua titulada por TTPa."),
    m("hidralazina", "Hidralazina injetável", "Anti-hipertensivo (vasodilatador)", INJ,
      ["EV", "IM"], [ap("Ampola 1 mL", 20, "mg/mL")],
      dose_min=0.1, dose_max=0.2, int_min=4, int_max=6, max_abs=20),
    m("hidrocortisona", "Hidrocortisona", "Corticosteroide", INJ,
      ["EV", "IM"], [ap("Frasco-ampola 100 mg", 100, "mg/frasco"), ap("Frasco-ampola 500 mg", 500, "mg/frasco")],
      dose_min=4, dose_max=8, int_min=6, int_max=6, max_dia_kg=32, max_abs=2000,
      obs="Usada em crise asmática e insuficiência adrenal."),
    m("lidocaina", "Lidocaína 2% sem vasoconstritor", "Anestésico local / Antiarrítmico", INJ,
      ["Infiltração", "EV (antiarrítmico)"], [ap("Frasco-ampola 20 mL", 20, "mg/mL")],
      dose_min=1, dose_max=1.5, int_min=None, int_max=None, max_abs=None,
      obs="Antiarrítmico (PCR/FV refratária): 1 mg/kg bolus EV. Infiltração: dose máx. local 4,5mg/kg."),
    m("meropenem", "Meropenem", "Antibiótico (Carbapenêmico)", INJ,
      ["EV"], [ap("Frasco-ampola 500 mg", 500, "mg/frasco"), ap("Frasco-ampola 1 g", 1000, "mg/frasco")],
      dose_min=20, dose_max=40, int_min=8, int_max=8, max_dia_kg=120, max_abs=6000,
      obs="Meningite: até 40mg/kg 8/8h (máx. 2g/dose)."),
    m("metilprednisolona", "Metilprednisolona", "Corticosteroide", INJ,
      ["EV", "IM"], [ap("Frasco-ampola 125 mg", 125, "mg/frasco"), ap("Frasco-ampola 500 mg", 500, "mg/frasco")],
      dose_min=1, dose_max=2, int_min=6, int_max=24, max_dia_kg=30, max_abs=1000,
      obs="Pulsoterapia (ex.: crise asmática grave) pode chegar a 30mg/kg/dia (máx. 1g)."),
    m("metronidazol_inj", "Metronidazol injetável", "Antibiótico / Antiparasitário", INJ,
      ["EV"], [ap("Bolsa 100 mL", 5, "mg/mL")],
      dose_min=7.5, dose_max=10, int_min=6, int_max=8, max_dia_kg=40, max_abs=4000),
    m("metoclopramida_inj", "Metoclopramida injetável", "Antiemético / Procinético", INJ,
      ["EV", "IM"], [ap("Ampola 2 mL", 5, "mg/mL")],
      dose_min=0.1, dose_max=0.15, int_min=8, int_max=8, max_dia_kg=0.5, max_abs=10,
      obs="Evitar em crianças pequenas; risco de reações extrapiramidais."),
    m("norepinefrina", "Norepinefrina (Noradrenalina)", "Vasopressor", INJ,
      ["EV (infusão contínua)"], [ap("Ampola 4 mL", 2, "mg/mL")],
      dose_min=0.05, dose_max=1, int_min=1, int_max=1,
      obs="Dose em mcg/kg/min (0,05-1), titulável, via exclusiva."),
    m("omeprazol_inj", "Omeprazol injetável", "Inibidor de bomba de prótons", INJ,
      ["EV"], [ap("Frasco-ampola 40 mg", 40, "mg/frasco")],
      dose_min=0.7, dose_max=1, int_min=24, int_max=24, max_abs=40),
    m("ondansetrona", "Ondansetrona", "Antiemético (antagonista 5-HT3)", INJ,
      ["EV", "VO"], [ap("Ampola 4 mL", 2, "mg/mL")],
      dose_min=0.1, dose_max=0.15, int_min=8, int_max=12, max_dia_kg=0.45, max_abs=16,
      obs="Prolonga intervalo QT; cautela com outros fármacos QT-prolongadores."),
    m("oxacilina", "Oxacilina", "Antibiótico (Penicilina resistente a penicilinase)", INJ,
      ["EV", "IM"], [ap("Frasco-ampola 500 mg", 500, "mg/frasco")],
      dose_min=100, dose_max=200, int_min=6, int_max=6, max_dia_kg=200, max_abs=12000),
    m("pantoprazol", "Pantoprazol", "Inibidor de bomba de prótons", INJ,
      ["EV"], [ap("Frasco-ampola 40 mg", 40, "mg/frasco")],
      dose_min=0.5, dose_max=1, int_min=24, int_max=24, max_abs=40),
    m("prometazina", "Prometazina", "Anti-histamínico / Antiemético", INJ,
      ["EV lento", "IM"], [ap("Ampola 2 mL", 25, "mg/mL")],
      dose_min=0.25, dose_max=0.5, int_min=6, int_max=8, max_abs=25,
      obs="Evitar em < 2 anos (risco de depressão respiratória grave)."),
    m("piperacilina_tazobactam", "Piperacilina + Tazobactam", "Antibiótico (Penicilina + Inibidor de betalactamase)", INJ,
      ["EV"], [ap("Frasco-ampola 4g + 500mg", 4000, "mg/frasco")],
      dose_min=240, dose_max=400, int_min=6, int_max=8, max_abs=16000,
      obs="Dose calculada com base no componente piperacilina."),
    m("salbutamol_inj", "Salbutamol injetável", "Broncodilatador (beta-2 agonista)", INJ,
      ["EV"], [ap("Ampola 1 mL", 0.5, "mg/mL")],
      dose_min=0.005, dose_max=0.01, int_min=None, int_max=None,
      obs="Uso restrito a broncoespasmo grave refratário, sob monitorização em UTI."),
    m("sulfametoxazol_trimetoprima_inj", "Sulfametoxazol + Trimetoprima injetável", "Antibiótico", INJ,
      ["EV"], [ap("Ampola 5 mL", 96, "mg/mL")],
      dose_min=8, dose_max=10, int_min=12, int_max=12, max_abs=None,
      obs="Dose calculada com base no componente trimetoprima (8-10mg/kg/dia)."),
    m("suxametonio", "Suxametônio (Succinilcolina)", "Bloqueador neuromuscular despolarizante", INJ,
      ["EV", "IM"], [ap("Frasco-ampola", 100, "mg/frasco")],
      dose_min=1, dose_max=2, int_min=None, int_max=None, max_abs=None,
      obs="Uso exclusivo em intubação de sequência rápida por profissional habilitado."),
    m("tenoxicam", "Tenoxicam", "Anti-inflamatório não esteroidal (AINE)", INJ,
      ["EV", "IM"], [ap("Frasco-ampola 20 mg", 20, "mg/frasco"), ap("Frasco-ampola 40 mg", 40, "mg/frasco")],
      dose_min=0.4, dose_max=0.4, int_min=24, int_max=24, max_abs=40,
      obs="Uso não rotineiro em pediatria; avaliar risco-benefício."),
    m("vancomicina", "Vancomicina", "Antibiótico (Glicopeptídeo)", INJ,
      ["EV"], [ap("Frasco-ampola 500 mg", 500, "mg/frasco")],
      dose_min=10, dose_max=15, int_min=6, int_max=8, max_dia_kg=60, max_abs=4000,
      obs="Infundir em no mínimo 60 minutos (síndrome do pescoço vermelho). Monitorar função renal."),
    m("vitaminas_complexo_b_inj", "Vitaminas do Complexo B injetável", "Vitamina", INJ,
      ["EV", "IM"], [ap("Ampola 2 mL", 1, "mg/mL")],
      obs="Reposição; sem faixa mg/kg padronizada — seguir protocolo institucional."),

    # ------------------------------------------------------ COMPRIMIDOS/CÁPSULAS
    m("aas", "Ácido Acetilsalicílico", "Antiagregante plaquetário / AINE", COMP,
      ["VO"], [ap("Comprimido 100 mg", 100, "mg/comprimido")],
      dose_min=3, dose_max=5, int_min=24, int_max=24, max_abs=100,
      obs="Antiagregante (ex.: Kawasaki fase crônica). Evitar em quadros virais (risco de Síndrome de Reye)."),
    m("acido_folico", "Ácido Fólico", "Vitamina", COMP,
      ["VO"], [ap("Comprimido 5 mg", 5, "mg/comprimido")],
      dose_min=0.5, dose_max=1, int_min=24, int_max=24, max_abs=5),
    m("albendazol_comp", "Albendazol comprimido", "Antiparasitário", COMP,
      ["VO"], [ap("Comprimido 400 mg", 400, "mg/comprimido")],
      dose_min=400, dose_max=400, int_min=None, int_max=None, max_abs=400,
      obs="Dose fixa de 400mg (dose única) em > 2 anos, independente do peso."),
    m("alopurinol", "Alopurinol", "Inibidor da xantina oxidase", COMP,
      ["VO"], [ap("Comprimido 100 mg", 100, "mg/comprimido")],
      dose_min=5, dose_max=10, int_min=12, int_max=24, max_abs=300),
    m("anlodipino", "Anlodipino", "Anti-hipertensivo (bloqueador de canal de cálcio)", COMP,
      ["VO"], [ap("Comprimido 5 mg", 5, "mg/comprimido")],
      dose_min=0.1, dose_max=0.3, int_min=24, int_max=24, max_abs=10),
    m("azitromicina_comp", "Azitromicina comprimido", "Antibiótico (Macrolídeo)", COMP,
      ["VO"], [ap("Comprimido 500 mg", 500, "mg/comprimido")],
      dose_min=10, dose_max=10, int_min=24, int_max=24, max_abs=500,
      obs="Pode prolongar intervalo QT."),
    m("amoxicilina_comp", "Amoxicilina comprimido/cápsula", "Antibiótico (Penicilina)", COMP,
      ["VO"], [ap("Cápsula 500 mg", 500, "mg/comprimido")],
      dose_min=25, dose_max=50, int_min=8, int_max=12, max_dia_kg=90, max_abs=4000),
    m("baclofeno", "Baclofeno", "Relaxante muscular (espasticidade)", COMP,
      ["VO"], [ap("Comprimido 10 mg", 10, "mg/comprimido")],
      dose_min=0.3, dose_max=1.5, int_min=8, int_max=8, max_abs=60,
      obs="Iniciar com dose baixa e titular; retirada gradual (risco de síndrome de abstinência)."),
    m("captopril", "Captopril", "Anti-hipertensivo (IECA)", COMP,
      ["VO"], [ap("Comprimido 25 mg", 25, "mg/comprimido")],
      dose_min=0.3, dose_max=6, int_min=8, int_max=8, max_abs=450,
      obs="Iniciar com dose baixa (0,15-0,3mg/kg/dose) e titular. Monitorar potássio e função renal."),
    m("carbonato_calcio", "Carbonato de Cálcio", "Suplemento mineral", COMP,
      ["VO"], [ap("Comprimido 500 mg", 500, "mg/comprimido")],
      dose_min=45, dose_max=65, int_min=8, int_max=12, max_abs=2500,
      obs="Dose expressa em mg/kg/dia de cálcio elementar."),
    m("carvedilol", "Carvedilol", "Anti-hipertensivo (betabloqueador)", COMP,
      ["VO"], [ap("Comprimido 12,5 mg", 12.5, "mg/comprimido")],
      dose_min=0.05, dose_max=0.4, int_min=12, int_max=12, max_abs=25,
      obs="Insuficiência cardíaca pediátrica; titular lentamente."),
    m("cefalexina_comp", "Cefalexina comprimido", "Antibiótico (Cefalosporina 1ª geração)", COMP,
      ["VO"], [ap("Comprimido 500 mg", 500, "mg/comprimido")],
      dose_min=25, dose_max=50, int_min=6, int_max=6, max_dia_kg=100, max_abs=4000),
    m("ciprofloxacino_comp", "Ciprofloxacino comprimido", "Antibiótico (Quinolona)", COMP,
      ["VO"], [ap("Comprimido 500 mg", 500, "mg/comprimido")],
      dose_min=10, dose_max=15, int_min=12, int_max=12, max_abs=1500,
      obs="Uso restrito; risco de artropatia (avaliar risco-benefício em pediatria)."),
    m("dipirona_comp", "Dipirona comprimido", "Analgésico / Antipirético", COMP,
      ["VO"], [ap("Comprimido 500 mg", 500, "mg/comprimido")],
      dose_min=10, dose_max=25, int_min=6, int_max=6, max_dia_kg=100, max_abs=4000),
    m("espironolactona", "Espironolactona", "Diurético poupador de potássio", COMP,
      ["VO"], [ap("Comprimido 25 mg", 25, "mg/comprimido")],
      dose_min=1, dose_max=3, int_min=12, int_max=24, max_abs=100,
      obs="Monitorar potássio sérico, especialmente com IECA."),
    m("ibuprofeno_comp", "Ibuprofeno comprimido", "Anti-inflamatório não esteroidal (AINE)", COMP,
      ["VO"], [ap("Comprimido 300 mg", 300, "mg/comprimido")],
      dose_min=5, dose_max=10, int_min=6, int_max=8, max_dia_kg=40, max_abs=2400,
      obs="Evitar em < 6 meses, desidratação, doença renal ou varicela."),
    m("fluconazol_comp", "Fluconazol comprimido", "Antifúngico", COMP,
      ["VO"], [ap("Cápsula 150 mg", 150, "mg/comprimido")],
      dose_min=6, dose_max=12, int_min=24, int_max=24, max_abs=800),
    m("hidroclorotiazida", "Hidroclorotiazida", "Diurético tiazídico", COMP,
      ["VO"], [ap("Comprimido 25 mg", 25, "mg/comprimido")],
      dose_min=1, dose_max=2, int_min=12, int_max=24, max_abs=100),
    m("hidralazina_comp", "Hidralazina comprimido", "Anti-hipertensivo (vasodilatador)", COMP,
      ["VO"], [ap("Comprimido 25 mg", 25, "mg/comprimido")],
      dose_min=0.75, dose_max=3, int_min=6, int_max=6, max_abs=200),
    m("ivermectina", "Ivermectina", "Antiparasitário", COMP,
      ["VO"], [ap("Comprimido 6 mg", 6, "mg/comprimido")],
      dose_min=0.15, dose_max=0.2, int_min=None, int_max=None, max_abs=None,
      obs="Dose única. Evitar em crianças com < 15 kg."),
    m("levotiroxina", "Levotiroxina", "Hormônio tireoidiano", COMP,
      ["VO"], [ap("Comprimido 25 mcg", 0.025, "mg/comprimido"), ap("Comprimido 50 mcg", 0.05, "mg/comprimido")],
      dose_min=0.003, dose_max=0.006, int_min=24, int_max=24, max_abs=0.15,
      obs="Dose em mg/kg/dia equivalente (0,003-0,006 mg/kg/dia); varia muito com idade — RN pode precisar de dose maior por kg."),
    m("losartana", "Losartana", "Anti-hipertensivo (BRA)", COMP,
      ["VO"], [ap("Comprimido 50 mg", 50, "mg/comprimido")],
      dose_min=0.7, dose_max=1.4, int_min=24, int_max=24, max_abs=100),
    m("metronidazol_comp", "Metronidazol comprimido", "Antibiótico / Antiparasitário", COMP,
      ["VO"], [ap("Comprimido 250 mg", 250, "mg/comprimido")],
      dose_min=7.5, dose_max=10, int_min=8, int_max=8, max_dia_kg=40, max_abs=4000),
    m("omeprazol_comp", "Omeprazol cápsula", "Inibidor de bomba de prótons", COMP,
      ["VO"], [ap("Cápsula 20 mg", 20, "mg/comprimido")],
      dose_min=0.7, dose_max=1, int_min=24, int_max=24, max_abs=40),
    m("oseltamivir", "Oseltamivir", "Antiviral", COMP,
      ["VO"], [ap("Cápsula 30 mg", 30, "mg/comprimido"), ap("Cápsula 45 mg", 45, "mg/comprimido"), ap("Cápsula 75 mg", 75, "mg/comprimido")],
      dose_min=2, dose_max=3, int_min=12, int_max=12, max_abs=150,
      obs="Dosagem por faixa de peso conforme bula (não estritamente linear em mg/kg). Faixa ≥40kg: 75mg 12/12h. Tratamento por 5 dias."),
    m("prednisona", "Prednisona", "Corticosteroide", COMP,
      ["VO"], [ap("Comprimido 5 mg", 5, "mg/comprimido"), ap("Comprimido 20 mg", 20, "mg/comprimido")],
      dose_min=1, dose_max=2, int_min=12, int_max=24, max_dia_kg=2, max_abs=60),
    m("propranolol", "Propranolol", "Betabloqueador", COMP,
      ["VO"], [ap("Comprimido 40 mg", 40, "mg/comprimido")],
      dose_min=0.5, dose_max=1, int_min=8, int_max=8, max_abs=160,
      obs="Também usado em hemangiomas infantis (protocolo específico, iniciar internado)."),
    m("sildenafila", "Sildenafila", "Vasodilatador pulmonar (inibidor da PDE5)", COMP,
      ["VO"], [ap("Comprimido 25 mg", 25, "mg/comprimido")],
      dose_min=0.5, dose_max=1, int_min=8, int_max=8, max_abs=20,
      obs="Hipertensão pulmonar; iniciar com dose baixa."),

    # ---------------------------------------------------- SUSPENSÕES/SOLUÇÕES
    m("albendazol_susp", "Albendazol suspensão", "Antiparasitário", SUSP,
      ["VO"], [ap("Suspensão oral 40 mg/mL", 40, "mg/mL")],
      dose_min=400, dose_max=400, int_min=None, int_max=None, max_abs=400,
      obs="Dose fixa de 400mg (dose única) em > 2 anos."),
    m("amoxicilina_clavulanato_susp", "Amoxicilina + Clavulanato suspensão", "Antibiótico (Penicilina + Inibidor de betalactamase)", SUSP,
      ["VO"], [ap("Suspensão oral 250+62,5mg/5mL", 50, "mg/mL")],
      dose_min=20, dose_max=45, int_min=8, int_max=12, max_dia_kg=90, max_abs=4000,
      obs="Dose calculada com base no componente amoxicilina."),
    m("amoxicilina_susp", "Amoxicilina suspensão", "Antibiótico (Penicilina)", SUSP,
      ["VO"], [ap("Pó para suspensão 250mg/5mL", 50, "mg/mL")],
      dose_min=25, dose_max=50, int_min=8, int_max=12, max_dia_kg=90, max_abs=4000,
      obs="Dose alta (90mg/kg/dia) para otite média/pneumonia."),
    m("azitromicina_susp", "Azitromicina suspensão", "Antibiótico (Macrolídeo)", SUSP,
      ["VO"], [ap("Pó para suspensão 200mg/5mL", 40, "mg/mL")],
      dose_min=10, dose_max=10, int_min=24, int_max=24, max_abs=500),
    m("cefalexina_susp", "Cefalexina suspensão", "Antibiótico (Cefalosporina 1ª geração)", SUSP,
      ["VO"], [ap("Suspensão oral 250mg/mL", 250, "mg/mL")],
      dose_min=25, dose_max=50, int_min=6, int_max=6, max_dia_kg=100, max_abs=4000,
      obs="Conferir rótulo local: concentração pode ser 250mg/5mL (50mg/mL) — validar apresentação real do frasco."),
    m("claritromicina_susp", "Claritromicina suspensão", "Antibiótico (Macrolídeo)", SUSP,
      ["VO"], [ap("Suspensão oral 250mg/mL", 250, "mg/mL")],
      dose_min=7.5, dose_max=7.5, int_min=12, int_max=12, max_dia_kg=15, max_abs=1000,
      obs="Conferir rótulo local (provável 250mg/5mL = 50mg/mL). Inibidor do CYP3A4."),
    m("domperidona", "Domperidona", "Antiemético / Procinético", SUSP,
      ["VO"], [ap("Suspensão oral 1 mg/mL", 1, "mg/mL")],
      dose_min=0.25, dose_max=0.5, int_min=8, int_max=8, max_dia_kg=2.4, max_abs=None,
      obs="Risco de prolongamento de QT; uso pelo menor tempo possível."),
    m("glicerina_enema", "Glicerina 12% solução enema", "Laxante", SUSP,
      ["Retal"], [ap("Frasco 500 mL", 120, "mg/mL")],
      obs="Uso retal para constipação; volume conforme idade, sem faixa mg/kg."),
    m("hidroxido_aluminio", "Hidróxido de Alumínio 6%", "Antiácido", SUSP,
      ["VO"], [ap("Suspensão oral 60 mg/mL", 60, "mg/mL")],
      dose_min=5, dose_max=15, int_min=6, int_max=8, max_abs=None,
      obs="Dose em mL/kg/dose (5-15 mL conforme idade em uso adulto); ajustar conforme protocolo pediátrico local."),
    m("benzoilmetronidazol", "Benzoilmetronidazol (Metronidazol Benzoato) suspensão", "Antiparasitário", SUSP,
      ["VO"], [ap("Suspensão oral 40 mg/mL", 40, "mg/mL")],
      dose_min=7.5, dose_max=10, int_min=8, int_max=8, max_dia_kg=40, max_abs=4000,
      obs="Equivalente ao metronidazol base; usado em giardíase/amebíase."),
    m("nistatina_susp", "Nistatina suspensão oral", "Antifúngico", SUSP,
      ["VO (tópico oral)"], [ap("Suspensão oral 100.000 UI/mL", 100000, "UI/mL")],
      dose_min=100000, dose_max=100000, int_min=6, int_max=6, max_abs=None,
      obs="Dose em UI (não mg/kg): 100.000-400.000 UI/dose, bochechar e engolir."),
    m("oleo_mineral", "Óleo Mineral", "Laxante lubrificante", SUSP,
      ["VO"], [ap("Solução oral", 1, "mL/mL")],
      obs="Dose por mL/kg conforme protocolo; evitar em < 1 ano (risco de aspiração)."),
    m("prednisolona_susp", "Prednisolona suspensão", "Corticosteroide", SUSP,
      ["VO"], [ap("Suspensão oral 3 mg/mL", 3, "mg/mL")],
      dose_min=1, dose_max=2, int_min=12, int_max=24, max_dia_kg=2, max_abs=60),
    m("sulfametoxazol_trimetoprima_susp", "Sulfametoxazol + Trimetoprima suspensão", "Antibiótico", SUSP,
      ["VO"], [ap("Suspensão oral 200+40mg/5mL", 8, "mg/mL")],
      dose_min=8, dose_max=10, int_min=12, int_max=12, max_abs=None,
      obs="Dose calculada com base no componente trimetoprima (8-10mg/kg/dia)."),
    m("sais_reidratacao_oral", "Sais para Reidratação Oral", "Reidratante", SUSP,
      ["VO"], [ap("Envelope (pó para diluir)", 1, "envelope")],
      obs="Diluir conforme instrução do envelope; oferecer livre demanda conforme protocolo de reidratação."),
    m("modulo_tcm", "Módulo de Triglicerídeo de Cadeia Média (TCM)", "Suplemento nutricional", SUSP,
      ["VO", "Enteral"], [ap("Frasco", 1, "mL/mL")],
      obs="Suplementação calórica conforme prescrição nutricional individualizada."),

    # ---------------------------------------------------------- GOTAS/EMULSÃO
    m("acido_ascorbico_gts", "Ácido Ascórbico (Vitamina C) gotas", "Vitamina", GTS,
      ["VO"], [ap("Solução oral gotas 200 mg/mL", 200, "mg/mL")],
      dose_min=1, dose_max=3, int_min=24, int_max=24, max_abs=500),
    m("bromoprida_gts", "Bromoprida gotas", "Antiemético / Procinético", GTS,
      ["VO"], [ap("Solução oral gotas 4 mg/mL", 4, "mg/mL")],
      dose_min=0.5, dose_max=1, int_min=8, int_max=8, max_dia_kg=3,
      obs="Evitar em < 1 ano; risco de reações extrapiramidais."),
    m("dipirona_gts", "Dipirona gotas", "Analgésico / Antipirético", GTS,
      ["VO"], [ap("Solução oral gotas 500 mg/mL", 500, "mg/mL")],
      dose_min=10, dose_max=25, int_min=6, int_max=6, max_dia_kg=100, max_abs=4000),
    m("ibuprofeno_gts", "Ibuprofeno gotas", "Anti-inflamatório não esteroidal (AINE)", GTS,
      ["VO"], [ap("Solução oral gotas 50 mg/mL", 50, "mg/mL")],
      dose_min=5, dose_max=10, int_min=6, int_max=8, max_dia_kg=40, max_abs=2400,
      obs="Evitar em < 6 meses, desidratação, doença renal ou varicela."),
    m("metoclopramida_gts", "Metoclopramida gotas", "Antiemético / Procinético", GTS,
      ["VO"], [ap("Solução oral gotas 4 mg/mL", 4, "mg/mL")],
      dose_min=0.1, dose_max=0.15, int_min=8, int_max=8, max_dia_kg=0.5, max_abs=10,
      obs="Evitar em crianças pequenas; risco de reações extrapiramidais."),
    m("paracetamol", "Paracetamol gotas", "Analgésico / Antipirético", GTS,
      ["VO"], [ap("Solução oral gotas 200 mg/mL", 200, "mg/mL")],
      dose_min=10, dose_max=15, int_min=4, int_max=6, max_dia_kg=75, max_abs=4000,
      obs="Não exceder 5 doses/dia. Ajustar em hepatopatas."),
    m("simeticona", "Simeticona", "Antiflatulento", GTS,
      ["VO"], [ap("Emulsão oral gotas 75 mg/mL", 75, "mg/mL")],
      dose_min=1.5, dose_max=3, int_min=8, int_max=8, max_abs=None,
      obs="Dose baixo risco; sem toxicidade relevante em excesso — ajustar por conforto clínico."),
    m("sulfato_ferroso", "Sulfato Ferroso gotas", "Suplemento mineral (ferro)", GTS,
      ["VO"], [ap("Solução oral gotas 125 mg/mL (25mg Fe/mL)", 25, "mg/mL")],
      dose_min=3, dose_max=6, int_min=12, int_max=24, max_abs=None,
      obs="Dose expressa em mg/kg/dia de ferro elementar (3-6mg/kg/dia para tratamento de anemia)."),
    m("vitaminas_complexo_b_gts", "Vitaminas do Complexo B gotas", "Vitamina", GTS,
      ["VO"], [ap("Solução oral gotas", 1, "mL/mL")],
      obs="Suplementação; sem faixa mg/kg padronizada — seguir posologia do rótulo."),

    # -------------------------------------------------------- XAROPES/ELIXIR
    m("ambroxol_adulto", "Ambroxol xarope adulto", "Mucolítico", XPE,
      ["VO"], [ap("Xarope 6 mg/mL (30mg/5mL)", 6, "mg/mL")],
      dose_min=1.2, dose_max=1.6, int_min=8, int_max=12, max_abs=90),
    m("ambroxol_pediatrico", "Ambroxol xarope pediátrico", "Mucolítico", XPE,
      ["VO"], [ap("Xarope 3 mg/mL (15mg/5mL)", 3, "mg/mL")],
      dose_min=1.2, dose_max=1.6, int_min=8, int_max=12, max_abs=45),
    m("dexclorfeniramina", "Dexclorfeniramina xarope", "Anti-histamínico (1ª geração)", XPE,
      ["VO"], [ap("Xarope 0,4 mg/mL", 0.4, "mg/mL")],
      dose_min=0.15, dose_max=0.2, int_min=8, int_max=8, max_abs=12),
    m("hidroxizine", "Hidroxizine xarope", "Anti-histamínico / Ansiolítico", XPE,
      ["VO"], [ap("Xarope 2 mg/mL", 2, "mg/mL")],
      dose_min=0.5, dose_max=1, int_min=8, int_max=8, max_abs=100),
    m("lactulose", "Lactulose", "Laxante osmótico", XPE,
      ["VO"], [ap("Solução oral 667 mg/mL", 667, "mg/mL")],
      dose_min=1, dose_max=2, int_min=12, int_max=24, max_abs=None,
      obs="Dose em mL/kg/dia (1-2 mL/kg/dia), titular conforme resposta."),
    m("salbutamol_xarope", "Salbutamol xarope", "Broncodilatador (beta-2 agonista)", XPE,
      ["VO"], [ap("Xarope 0,4 mg/mL", 0.4, "mg/mL")],
      dose_min=0.1, dose_max=0.15, int_min=6, int_max=8, max_dia_kg=0.6, max_abs=20),
    m("dexametasona_elixir", "Dexametasona elixir", "Corticosteroide", XPE,
      ["VO"], [ap("Elixir 0,1 mg/mL", 0.1, "mg/mL")],
      dose_min=0.15, dose_max=0.6, int_min=6, int_max=12, max_abs=16,
      obs="Uso comum em laringite/crupe (dose única 0,15-0,6 mg/kg)."),
    m("loratadina", "Loratadina xarope", "Anti-histamínico (2ª geração)", XPE,
      ["VO"], [ap("Xarope 1 mg/mL", 1, "mg/mL")],
      dose_min=0.15, dose_max=0.3, int_min=24, int_max=24, max_abs=10),
    m("cloreto_potassio_xarope", "Cloreto de Potássio xarope", "Suplemento eletrolítico", XPE,
      ["VO"], [ap("Xarope 60 mg/mL (6%)", 60, "mg/mL")],
      dose_min=1, dose_max=3, int_min=8, int_max=12, max_abs=None,
      obs="Dose expressa em mEq/kg/dia; diluir bem, monitorar potássio sérico."),

    # --------------------------------------------- POMADAS/CREMES/LOÇÕES (tópicos)
    m("dexametasona_creme", "Dexametasona creme", "Corticosteroide tópico", TOP,
      ["Tópica"], [ap("Bisnaga 1 mg/g", 1, "mg/g")], obs="Uso tópico; sem cálculo de dose sistêmica."),
    m("lidocaina_gel", "Lidocaína 2% gel", "Anestésico local tópico", TOP,
      ["Tópica"], [ap("Bisnaga 30 g", 20, "mg/g")], obs="Uso tópico; atenção à dose máxima cumulativa em mucosas extensas."),
    m("miconazol_derma", "Miconazol dermatológico creme", "Antifúngico tópico", TOP,
      ["Tópica"], [ap("Bisnaga 28 g", 20, "mg/g")], obs="Uso tópico."),
    m("miconazol_ginecologico", "Miconazol ginecológico creme", "Antifúngico tópico", TOP,
      ["Tópica/Vaginal"], [ap("Bisnaga 80 g", 20, "mg/g")], obs="Uso tópico/vaginal."),
    m("mupirocina", "Mupirocina creme", "Antibiótico tópico", TOP,
      ["Tópica"], [ap("Bisnaga 15 g", 20, "mg/g")], obs="Uso tópico."),
    m("neomicina_bacitracina", "Neomicina + Bacitracina pomada", "Antibiótico tópico", TOP,
      ["Tópica"], [ap("Bisnaga 15 g", 1, "g/g")], obs="Uso tópico em pequenas feridas/lesões."),
    m("nistatina_oxido_zinco", "Nistatina + Óxido de Zinco creme", "Antifúngico tópico / Protetor cutâneo", TOP,
      ["Tópica"], [ap("Creme (100.000 UI + 200mg/g)", 100000, "UI/g")], obs="Uso tópico em dermatite de fralda."),
    m("oxido_zinco_pasta", "Óxido de Zinco (Pasta d'água)", "Protetor cutâneo", TOP,
      ["Tópica"], [ap("Frasco 100 g", 1, "g/g")], obs="Uso tópico."),
    m("oxido_zinco_vit_a_d", "Óxido de Zinco + Vit. A + Vit. D pomada", "Protetor cutâneo", TOP,
      ["Tópica"], [ap("Bisnaga 45 g", 1, "g/g")], obs="Uso tópico em dermatite de fralda."),
    m("creme_barreira", "Creme Barreira (Protetor Cutâneo)", "Protetor cutâneo", TOP,
      ["Tópica"], [ap("Bisnaga", 1, "g/g")], obs="Uso tópico preventivo (lesão por pressão/umidade)."),
    m("deltrametrina", "Deltrametrina xampu", "Antiparasitário tópico (pediculicida)", TOP,
      ["Tópica (couro cabeludo)"], [ap("Frasco 0,2 mg/mL", 0.2, "mg/mL")], obs="Uso tópico único; repetir em 7 dias se necessário."),
    m("permetrina", "Permetrina 5% loção cremosa", "Antiparasitário tópico (escabicida)", TOP,
      ["Tópica"], [ap("Frasco 50 mg/mL", 50, "mg/mL")], obs="Aplicar em todo o corpo, deixar agir 8-12h; uso permitido a partir de 2 meses."),

    # ------------------------------------------------------------ INALATÓRIOS
    m("beclometasona_inal", "Beclometasona inalatória", "Corticosteroide inalatório", INAL,
      ["Inalatória"], [ap("Flaconete 2 mL", 1, "mg/mL")],
      obs="Dose por protocolo de manutenção (asma); não é dose de resgate agudo."),
    m("brometo_ipratropio", "Brometo de Ipratrópio", "Broncodilatador (anticolinérgico)", INAL,
      ["Inalatória (nebulização)"], [ap("Solução inalatória 0,25 mg/mL", 0.25, "mg/mL")],
      dose_min=0.25, dose_max=0.5, int_min=6, int_max=8, max_abs=None,
      obs="Dose fixa por nebulização (250-500mcg), não por peso, em crianças > 12 anos/adultos; crianças menores usar 125-250mcg."),
    m("cloreto_sodio_inal", "Cloreto de Sódio 0,9% inalatório", "Veículo / Solução para nebulização", INAL,
      ["Inalatória"], [ap("Frasco 30 mL", 9, "mg/mL")], obs="Usado como diluente para nebulização; sem dose própria."),
    m("salbutamol_nebulizacao", "Salbutamol solução para nebulização", "Broncodilatador (beta-2 agonista)", INAL,
      ["Inalatória (nebulização)"], [ap("Frasco 10 mL", 5, "mg/mL")],
      dose_min=0.1, dose_max=0.15, int_min=4, int_max=6, max_abs=5,
      obs="Dose de nebulização usual: 2,5-5mg/dose (mín. 2,5mg), independente do peso em muitos protocolos."),
    m("salbutamol_spray", "Salbutamol spray aerossol", "Broncodilatador (beta-2 agonista)", INAL,
      ["Inalatória (spray)"], [ap("Frasco 200 doses (100mcg/jato)", 0.1, "mg/jato")],
      dose_min=1, dose_max=2, int_min=4, int_max=6, max_abs=None,
      obs="1-2 jatos (100-200mcg) por administração, preferencialmente com espaçador."),

    # -------------------------------------------------------------- OFTÁLMICOS
    m("dextrano_hipromelose", "Dextrano + Hipromelose + Glicerol", "Lubrificante ocular", OFT,
      ["Oftálmica"], [ap("Frasco 15 mL", 1, "mL/mL")], obs="Lágrima artificial; sem dose sistêmica."),
    m("tobramicina_oftalmica", "Tobramicina solução oftálmica", "Antibiótico tópico ocular", OFT,
      ["Oftálmica"], [ap("Frasco 5 mL", 3, "mg/mL")], obs="1-2 gotas conforme prescrição; uso tópico."),
    m("tropicamida", "Tropicamida solução oftálmica", "Midriático/Cicloplégico", OFT,
      ["Oftálmica"], [ap("Frasco 5 mL", 10, "mg/mL")], obs="Uso para exame de fundo de olho; uso tópico."),
    m("ciprofloxacino_oftalmico", "Ciprofloxacino oftálmico", "Antibiótico tópico ocular", OFT,
      ["Oftálmica"], [ap("Frasco", 3, "mg/mL")], obs="Uso tópico."),

    # -------------------------------------------------------------- ELETRÓLITOS
    m("agua_destilada", "Água Destilada", "Diluente", ELET,
      ["EV (diluente)"], [ap("Ampola 10 mL", 0, "mL/mL")], obs="Uso exclusivo como diluente/veículo."),
    m("cloreto_potassio_10", "Cloreto de Potássio 10%", "Reposição eletrolítica", ELET,
      ["EV (diluído)"], [ap("Ampola 10 mL", 100, "mg/mL")],
      dose_min=0.5, dose_max=1, int_min=None, int_max=None, max_abs=None,
      obs="NUNCA administrar em bolus/sem diluição — risco de parada cardíaca. Dose em mEq/kg, infusão controlada."),
    m("cloreto_sodio_10", "Cloreto de Sódio 10%", "Reposição eletrolítica", ELET,
      ["EV (diluído)"], [ap("Ampola 10 mL", 100, "mg/mL")],
      obs="Aditivo para correção de sódio; diluir e calcular conforme déficit calculado individualmente."),
    m("gliconato_calcio", "Gliconato de Cálcio 10%", "Reposição eletrolítica / Antídoto (hipercalemia)", ELET,
      ["EV lento"], [ap("Ampola 10 mL", 100, "mg/mL")],
      dose_min=0.5, dose_max=1, int_min=None, int_max=None, max_abs=3000,
      obs="Infundir lentamente com monitorização cardíaca; extravasamento causa necrose tecidual."),
    m("glicose_50", "Glicose 50%", "Reposição de glicose / Antídoto (hipoglicemia)", ELET,
      ["EV"], [ap("Ampola 10 mL", 500, "mg/mL")],
      dose_min=0.5, dose_max=1, int_min=None, int_max=None, max_abs=None,
      obs="Hipoglicemia: 0,5-1 g/kg diluído (evitar concentração > 12,5% em acesso periférico/neonatos)."),
    m("sulfato_magnesio", "Sulfato de Magnésio", "Reposição eletrolítica / Broncodilatador adjuvante / Anticonvulsivante", ELET,
      ["EV"], [ap("Ampola 10 mL", 100, "mg/mL")],
      dose_min=25, dose_max=50, int_min=4, int_max=6, max_dia_kg=200, max_abs=2000,
      obs="Infundir lentamente (risco de hipotensão). Monitorar reflexos e frequência respiratória."),
    m("manitol", "Manitol 20%", "Diurético osmótico", ELET,
      ["EV"], [ap("Bolsa 250 mL", 200, "mg/mL")],
      dose_min=0.25, dose_max=1, int_min=4, int_max=6, max_abs=None,
      obs="Uso em hipertensão intracraniana; monitorar osmolaridade sérica e função renal."),

    # -------------------------------------------------------------- CONTRASTES
    m("contraste_nao_ionico", "Contraste Radiológico Não Iônico (Iobitriol/Iopamidol)", "Meio de contraste", CONT,
      ["EV"], [ap("Frasco", 1, "mL/mL")], obs="Dose calculada pelo radiologista conforme exame e peso; sem faixa mg/kg de uso geral."),
    m("contraste_meglumina", "Contraste Radiológico Iônico (Meglumina)", "Meio de contraste", CONT,
      ["EV"], [ap("Frasco 50 mL", 1, "mL/mL")], obs="Dose calculada pelo radiologista conforme exame."),
    m("sulfato_bario", "Sulfato de Bário", "Meio de contraste (via oral)", CONT,
      ["VO"], [ap("Suspensão oral 150 mL", 1, "mL/mL")], obs="Uso exclusivo para exames contrastados do trato digestivo."),

    # -------------------------------------------------------------- TERMOLÁBEIS
    m("anfotericina_b", "Anfotericina B (desoxicolato)", "Antifúngico", TERM,
      ["EV"], [ap("Frasco-ampola 50 mg", 50, "mg/frasco")],
      dose_min=0.25, dose_max=1, int_min=24, int_max=24, max_abs=None,
      obs="Nefrotóxica; infundir lentamente, pré-hidratar, monitorar eletrólitos e função renal."),
    m("atracurio", "Atracúrio", "Bloqueador neuromuscular não despolarizante", TERM,
      ["EV"], [ap("Ampola 5 mL", 10, "mg/mL")],
      dose_min=0.3, dose_max=0.6, int_min=None, int_max=None, max_abs=None,
      obs="Uso exclusivo sob monitorização (anestesia/UTI) por profissional habilitado."),
    m("insulina_regular", "Insulina Regular (Humana)", "Hormônio / Antidiabético", TERM,
      ["EV", "SC"], [ap("Frasco-ampola 100 UI/mL", 100, "UI/mL")],
      dose_min=0.05, dose_max=0.1, int_min=1, int_max=1, max_dia_kg=2.4,
      obs="Dose expressa em UI/kg/h (infusão contínua em cetoacidose diabética: 0,05-0,1 UI/kg/h)."),
    m("insulina_nph", "Insulina NPH", "Hormônio / Antidiabético (ação intermediária)", TERM,
      ["SC"], [ap("Frasco-ampola 100 UI/mL", 100, "UI/mL")],
      dose_min=0.5, dose_max=1, int_min=12, int_max=24, max_dia_kg=1.5,
      obs="Dose expressa em UI/kg/dia; individualizar conforme monitorização glicêmica."),
    m("pancuronio", "Pancurônio", "Bloqueador neuromuscular não despolarizante", TERM,
      ["EV"], [ap("Ampola 2 mL", 2, "mg/mL")],
      dose_min=0.08, dose_max=0.1, int_min=None, int_max=None, max_abs=None,
      obs="Uso exclusivo sob monitorização (anestesia/UTI) por profissional habilitado."),
    m("rocuronio", "Rocurônio", "Bloqueador neuromuscular não despolarizante", TERM,
      ["EV"], [ap("Solução injetável 10 mg/mL", 10, "mg/mL")],
      dose_min=0.6, dose_max=1.2, int_min=None, int_max=None, max_abs=None,
      obs="Intubação de sequência rápida; uso exclusivo por profissional habilitado."),
    m("glicerina_supositorio", "Glicerina Supositório", "Laxante", TERM,
      ["Retal"], [ap("Supositório", 1, "unidade")], obs="Uso retal para constipação; sem cálculo de mg/kg."),

    # ------------------------------------------------- ANTIMICROBIANOS DE RESERVA
    m("anfotericina_lipossomal", "Anfotericina B Lipossomal", "Antifúngico (formulação lipídica)", RESERVA,
      ["EV"], [ap("Frasco-ampola 50 mg", 50, "mg/frasco")],
      dose_min=3, dose_max=5, int_min=24, int_max=24, max_abs=None,
      obs="Menos nefrotóxica que a formulação convencional; ainda assim monitorar função renal."),
    m("caspofungina", "Caspofungina", "Antifúngico (Equinocandina)", RESERVA,
      ["EV"], [ap("Frasco-ampola 50 mg", 50, "mg/frasco")],
      dose_min=50, dose_max=70, int_min=24, int_max=24, max_abs=70,
      obs="Dose de ataque 70mg/m² (dia 1), manutenção 50mg/m²/dia — aqui aproximado por mg/kg para triagem; validar com farmácia."),
    m("linezolida", "Linezolida", "Antibiótico (Oxazolidinona)", RESERVA,
      ["EV", "VO"], [ap("Bolsa 600 mg", 2, "mg/mL")],
      dose_min=10, dose_max=10, int_min=8, int_max=8, max_abs=600,
      obs="Risco de síndrome serotoninérgica com ISRS/tramadol/opioides serotonérgicos. Monitorar hemograma (mielossupressão)."),
    m("micafungina", "Micafungina", "Antifúngico (Equinocandina)", RESERVA,
      ["EV"], [ap("Frasco-ampola 50 mg", 50, "mg/frasco"), ap("Frasco-ampola 100 mg", 100, "mg/frasco")],
      dose_min=2, dose_max=4, int_min=24, int_max=24, max_abs=None),
    m("polimixina_b", "Polimixina B", "Antibiótico (Polimixina)", RESERVA,
      ["EV"], [ap("Frasco-ampola 500.000 UI", 500000, "UI/frasco")],
      dose_min=15000, dose_max=25000, int_min=12, int_max=12, max_abs=None,
      obs="Dose em UI/kg/dia. Nefrotóxica; monitorar função renal."),
    m("teicoplanina", "Teicoplanina", "Antibiótico (Glicopeptídeo)", RESERVA,
      ["EV", "IM"], [ap("Frasco-ampola 400 mg", 400, "mg/frasco"), ap("Frasco-ampola 200 mg", 200, "mg/frasco")],
      dose_min=6, dose_max=10, int_min=12, int_max=24, max_abs=None,
      obs="Dose de ataque a cada 12h nas primeiras 3 doses, depois 1x/dia."),
    m("tigeciclina", "Tigeciclina", "Antibiótico (Glicilciclina)", RESERVA,
      ["EV"], [ap("Frasco-ampola 50 mg", 50, "mg/frasco")],
      dose_min=1, dose_max=2, int_min=12, int_max=12, max_abs=100,
      obs="Uso restrito/reserva; experiência pediátrica limitada — avaliar com infectologia."),

    # ---------------------------------------------------- CONTROLADOS INJETÁVEIS
    m("clorpromazina", "Clorpromazina", "Antipsicótico", CTRL_INJ,
      ["EV lento", "IM"], [ap("Ampola 5 mL", 5, "mg/mL")],
      dose_min=0.5, dose_max=1, int_min=6, int_max=8, max_abs=75),
    m("dexmedetomidina", "Dexmedetomidina", "Sedativo (agonista alfa-2)", CTRL_INJ,
      ["EV (infusão contínua)"], [ap("Frasco-ampola 2 mL", 0.1, "mg/mL")],
      dose_min=0.2, dose_max=1.4, int_min=1, int_max=1,
      obs="Dose em mcg/kg/h (infusão contínua, titulável), pode usar dose de ataque 0,5-1mcg/kg em 10min."),
    m("diazepam_inj", "Diazepam injetável", "Benzodiazepínico", CTRL_INJ,
      ["EV lento", "Retal"], [ap("Ampola 2 mL", 5, "mg/mL")],
      dose_min=0.2, dose_max=0.5, int_min=6, int_max=12, max_abs=10,
      obs="Crise convulsiva aguda: 0,2-0,3mg/kg EV lento (máx. 10mg) ou 0,5mg/kg retal."),
    m("escetamina", "Escetamina (Cetamina S+)", "Anestésico dissociativo / Analgésico", CTRL_INJ,
      ["EV", "IM"], [ap("Frasco 10 mL", 50, "mg/mL")],
      dose_min=0.5, dose_max=2, int_min=None, int_max=None, max_abs=None,
      obs="Sedação/indução anestésica; uso por profissional habilitado com monitorização."),
    m("etomidato", "Etomidato", "Anestésico (indução)", CTRL_INJ,
      ["EV"], [ap("Frasco 10 mL", 2, "mg/mL")],
      dose_min=0.2, dose_max=0.3, int_min=None, int_max=None, max_abs=None,
      obs="Indução anestésica em sequência rápida; uso por profissional habilitado."),
    m("fenitoina", "Fenitoína", "Anticonvulsivante", CTRL_INJ,
      ["EV"], [ap("Ampola 5 mL", 50, "mg/mL")],
      dose_min=15, dose_max=20, int_min=24, int_max=24, max_abs=1500,
      obs="Dose de ataque (status epilepticus). Diluir em SF 0,9% (precipita em glicose); infundir devagar."),
    m("fenobarbital_inj", "Fenobarbital injetável", "Anticonvulsivante", CTRL_INJ,
      ["EV", "IM"], [ap("Ampola 2 mL", 100, "mg/mL")],
      dose_min=15, dose_max=20, int_min=24, int_max=24, max_abs=1000,
      obs="Dose de ataque em crise convulsiva. Risco de depressão respiratória, potencializado por outros depressores do SNC."),
    m("fentanil", "Fentanil", "Opioide (analgesia/sedação)", CTRL_INJ,
      ["EV"], [ap("Ampola 0,05mg/mL 2 mL", 0.05, "mg/mL"), ap("Ampola 0,05mg/mL 5 mL", 0.05, "mg/mL"), ap("Ampola 0,05mg/mL 10 mL", 0.05, "mg/mL")],
      dose_min=0.001, dose_max=0.002, int_min=1, int_max=2, max_abs=None,
      obs="Analgesia/sedação: 1-2 mcg/kg/dose; infusão contínua 0,5-2 mcg/kg/h em UTI."),
    m("flumazenil", "Flumazenil", "Antídoto (antagonista de benzodiazepínico)", CTRL_INJ,
      ["EV"], [ap("Ampola 5 mL", 0.1, "mg/mL")],
      dose_min=0.01, dose_max=0.01, int_min=None, int_max=None, max_abs=0.2,
      obs="Reversão de sedação por benzodiazepínico; pode repetir a cada minuto até máx. 1mg."),
    m("haloperidol_inj", "Haloperidol injetável", "Antipsicótico", CTRL_INJ,
      ["EV", "IM"], [ap("Ampola 1 mL", 5, "mg/mL")],
      dose_min=0.025, dose_max=0.075, int_min=8, int_max=12, max_abs=5,
      obs="Uso pediátrico restrito; monitorar QT e sintomas extrapiramidais."),
    m("haloperidol_decanoato", "Haloperidol Decanoato", "Antipsicótico (depósito)", CTRL_INJ,
      ["IM"], [ap("Ampola 1 mL", 50, "mg/mL")],
      obs="Formulação de depósito (ação prolongada); uso raro em pediatria — decisão de psiquiatria."),
    m("midazolam", "Midazolam", "Benzodiazepínico / Sedativo", CTRL_INJ,
      ["EV", "IM", "Nasal"], [ap("Ampola 5mg/mL 3 mL", 5, "mg/mL"), ap("Ampola 1mg/mL 5 mL", 1, "mg/mL"), ap("Ampola 5mg/mL 10 mL", 5, "mg/mL")],
      dose_min=0.1, dose_max=0.3, int_min=4, int_max=6, max_abs=10,
      obs="Depressor de SNC; risco de depressão respiratória associado a opioides."),
    m("morfina", "Morfina", "Opioide", CTRL_INJ,
      ["EV", "SC", "IM"], [ap("Ampola 0,2mg/mL 1 mL (diluída)", 0.2, "mg/mL"), ap("Ampola 10mg/mL 1 mL", 10, "mg/mL")],
      dose_min=0.05, dose_max=0.1, int_min=4, int_max=4, max_abs=15,
      obs="Monitorar sedação e depressão respiratória, especialmente com outros depressores do SNC. Apresentação diluída (0,2mg/mL) útil para doses pequenas em neonatos/lactentes."),
    m("naloxona", "Naloxona", "Antídoto (antagonista opioide)", CTRL_INJ,
      ["EV", "IM", "SC"], [ap("Ampola 1 mL", 0.4, "mg/mL")],
      dose_min=0.01, dose_max=0.1, int_min=2, int_max=3, max_abs=2,
      obs="Repetir conforme necessário; meia-vida curta pode exigir doses repetidas/infusão."),
    m("remifentanila", "Remifentanila", "Opioide de ação ultracurta", CTRL_INJ,
      ["EV (infusão contínua)"], [ap("Frasco (pó liófilo)", 1, "mg/frasco")],
      dose_min=0.05, dose_max=2, int_min=1, int_max=1,
      obs="Dose em mcg/kg/min, infusão contínua sob monitorização anestésica/UTI."),
    m("sugamadex", "Sugamadex Sódico", "Reversor de bloqueio neuromuscular", CTRL_INJ,
      ["EV"], [ap("Ampola 2 mL", 100, "mg/mL")],
      dose_min=2, dose_max=16, int_min=None, int_max=None, max_abs=None,
      obs="Dose depende do grau de bloqueio neuromuscular (2-4mg/kg de rotina; até 16mg/kg em reversão imediata)."),
    m("tramadol", "Tramadol", "Opioide (analgésico de ação central)", CTRL_INJ,
      ["EV", "IM"], [ap("Ampola 50mg/mL 2 mL", 50, "mg/mL"), ap("Ampola 50mg/mL 1 mL", 50, "mg/mL")],
      dose_min=1, dose_max=2, int_min=6, int_max=8, max_dia_kg=8, max_abs=400,
      obs="Reduz limiar convulsivo; risco de síndrome serotoninérgica com outros serotonérgicos."),

    # -------------------------------------------------- CONTROLADOS ANESTÉSICOS
    m("propofol", "Propofol", "Anestésico / Sedativo", CTRL_ANEST,
      ["EV"], [ap("Frasco 20 mL", 10, "mg/mL")],
      dose_min=1, dose_max=2.5, int_min=None, int_max=None, max_abs=None,
      obs="Indução: 1-2,5mg/kg. Sedação contínua em mcg/kg/min sob monitorização; evitar infusão prolongada em crianças (risco de síndrome da infusão do propofol)."),
    m("sevoflurano", "Sevoflurano", "Anestésico inalatório", CTRL_ANEST,
      ["Inalatória"], [ap("Frasco 250 mL", 1, "mL/mL")],
      obs="Dosado por concentração expirada (%), não por mg/kg; uso exclusivo por anestesiologista."),
    m("tiopental", "Tiopental Sódico", "Anestésico (barbitúrico)", CTRL_ANEST,
      ["EV"], [ap("Frasco-ampola (pó p/ diluição)", 1000, "mg/frasco")],
      dose_min=3, dose_max=5, int_min=None, int_max=None, max_abs=None,
      obs="Indução anestésica/coma barbitúrico; uso exclusivo sob monitorização intensiva."),

    # ------------------------------------------------ CONTROLADOS ORAL/GOTAS
    m("carbamazepina_susp", "Carbamazepina solução oral", "Anticonvulsivante", CTRL_ORAL_GTS,
      ["VO"], [ap("Solução oral 20 mg/mL", 20, "mg/mL")],
      dose_min=5, dose_max=10, int_min=8, int_max=12, max_dia_kg=35, max_abs=1200,
      obs="Iniciar com dose baixa e titular lentamente."),
    m("clonazepam_gts", "Clonazepam gotas", "Benzodiazepínico / Anticonvulsivante", CTRL_ORAL_GTS,
      ["VO"], [ap("Solução oral gotas 2,5 mg/mL", 2.5, "mg/mL")],
      dose_min=0.01, dose_max=0.03, int_min=8, int_max=12, max_abs=None,
      obs="Iniciar com dose baixa; sedação e depressão respiratória em associação com outros depressores."),
    m("fenobarbital_susp", "Fenobarbital solução oral", "Anticonvulsivante", CTRL_ORAL_GTS,
      ["VO"], [ap("Solução oral 40 mg/mL", 40, "mg/mL")],
      dose_min=3, dose_max=6, int_min=12, int_max=24, max_abs=None,
      obs="Manutenção (dose de ataque é maior, via injetável)."),
    m("haloperidol_gts", "Haloperidol gotas", "Antipsicótico", CTRL_ORAL_GTS,
      ["VO"], [ap("Solução oral gotas 2 mg/mL", 2, "mg/mL")],
      dose_min=0.025, dose_max=0.075, int_min=8, int_max=12, max_abs=5),
    m("valproato_xarope", "Valproato de Sódio xarope", "Anticonvulsivante", CTRL_ORAL_GTS,
      ["VO"], [ap("Xarope 50 mg/mL", 50, "mg/mL")],
      dose_min=10, dose_max=15, int_min=8, int_max=12, max_dia_kg=60, max_abs=3000,
      obs="Hepatotoxicidade; monitorar função hepática. Contraindicado em suspeita de doença mitocondrial."),
    m("levetiracetam_susp", "Levetiracetam solução oral", "Anticonvulsivante", CTRL_ORAL_GTS,
      ["VO"], [ap("Solução oral 100 mg/mL", 100, "mg/mL")],
      dose_min=10, dose_max=30, int_min=12, int_max=12, max_dia_kg=60, max_abs=3000),

    # ------------------------------------------------- CONTROLADOS COMPRIMIDOS
    m("acido_ursodesoxicolico", "Ácido Ursodesoxicólico", "Colerético / Hepatoprotetor", CTRL_COMP,
      ["VO"], [ap("Comprimido 50 mg", 50, "mg/comprimido")],
      dose_min=10, dose_max=20, int_min=12, int_max=12, max_abs=None),
    m("carbamazepina_comp", "Carbamazepina comprimido", "Anticonvulsivante", CTRL_COMP,
      ["VO"], [ap("Comprimido 200 mg", 200, "mg/comprimido")],
      dose_min=5, dose_max=10, int_min=8, int_max=12, max_dia_kg=35, max_abs=1200),
    m("clobazam", "Clobazam", "Benzodiazepínico / Anticonvulsivante", CTRL_COMP,
      ["VO"], [ap("Comprimido 10 mg", 10, "mg/comprimido")],
      dose_min=0.2, dose_max=1, int_min=12, int_max=12, max_abs=40),
    m("clonazepam_comp", "Clonazepam comprimido", "Benzodiazepínico / Anticonvulsivante", CTRL_COMP,
      ["VO"], [ap("Comprimido 2 mg", 2, "mg/comprimido")],
      dose_min=0.01, dose_max=0.03, int_min=8, int_max=12, max_abs=None),
    m("diazepam_comp", "Diazepam comprimido", "Benzodiazepínico", CTRL_COMP,
      ["VO"], [ap("Comprimido 5 mg", 5, "mg/comprimido"), ap("Comprimido 10 mg", 10, "mg/comprimido")],
      dose_min=0.1, dose_max=0.3, int_min=8, int_max=12, max_abs=10),
    m("fenobarbital_comp", "Fenobarbital comprimido", "Anticonvulsivante", CTRL_COMP,
      ["VO"], [ap("Comprimido 100 mg", 100, "mg/comprimido")],
      dose_min=3, dose_max=6, int_min=12, int_max=24, max_abs=None),
    m("fluoxetina", "Fluoxetina", "Antidepressivo (ISRS)", CTRL_COMP,
      ["VO"], [ap("Comprimido 20 mg", 20, "mg/comprimido")],
      dose_min=0.25, dose_max=0.5, int_min=24, int_max=24, max_abs=60,
      obs="Uso a partir de 7-8 anos conforme indicação; iniciar com dose baixa."),
    m("haloperidol_comp", "Haloperidol comprimido", "Antipsicótico", CTRL_COMP,
      ["VO"], [ap("Comprimido 1 mg", 1, "mg/comprimido"), ap("Comprimido 5 mg", 5, "mg/comprimido")],
      dose_min=0.025, dose_max=0.075, int_min=8, int_max=12, max_abs=5),
    m("lamotrigina", "Lamotrigina", "Anticonvulsivante", CTRL_COMP,
      ["VO"], [ap("Comprimido 25 mg", 25, "mg/comprimido")],
      dose_min=0.15, dose_max=0.6, int_min=12, int_max=24, max_abs=None,
      obs="Titulação muito lenta e específica (risco de Stevens-Johnson); seguir protocolo detalhado."),
    m("levetiracetam_comp", "Levetiracetam comprimido", "Anticonvulsivante", CTRL_COMP,
      ["VO"], [ap("Comprimido 250 mg", 250, "mg/comprimido")],
      dose_min=10, dose_max=30, int_min=12, int_max=12, max_dia_kg=60, max_abs=3000),
    m("lorazepam", "Lorazepam", "Benzodiazepínico", CTRL_COMP,
      ["VO"], [ap("Comprimido 2 mg", 2, "mg/comprimido")],
      dose_min=0.02, dose_max=0.05, int_min=8, int_max=12, max_abs=4),
    m("metadona", "Metadona", "Opioide", CTRL_COMP,
      ["VO"], [ap("Comprimido 5 mg", 5, "mg/comprimido"), ap("Comprimido 10 mg", 10, "mg/comprimido")],
      dose_min=0.1, dose_max=0.2, int_min=6, int_max=12, max_abs=None,
      obs="Uso em desmame de opioides/dor crônica; meia-vida longa e variável — ajuste sob supervisão especializada."),
    m("risperidona", "Risperidona", "Antipsicótico", CTRL_COMP,
      ["VO"], [ap("Comprimido 1 mg", 1, "mg/comprimido"), ap("Comprimido 2 mg", 2, "mg/comprimido")],
      dose_min=0.01, dose_max=0.02, int_min=12, int_max=24, max_abs=6),
    m("topiramato", "Topiramato", "Anticonvulsivante", CTRL_COMP,
      ["VO"], [ap("Comprimido 25 mg", 25, "mg/comprimido"), ap("Comprimido 100 mg", 100, "mg/comprimido")],
      dose_min=1, dose_max=9, int_min=12, int_max=12, max_abs=400,
      obs="Iniciar com dose baixa e titular lentamente."),
]


def main():
    ids = [med["id"] for med in MEDICAMENTOS]
    duplicados = {i for i in ids if ids.count(i) > 1}
    if duplicados:
        raise SystemExit(f"IDs duplicados encontrados: {duplicados}")

    ids_invalidos = set(PORTARIA_344) - set(ids)
    if ids_invalidos:
        raise SystemExit(f"PORTARIA_344 referencia id(s) inexistente(s): {ids_invalidos}")
    ids_invalidos = USO_COLETIVO_IDS - set(ids)
    if ids_invalidos:
        raise SystemExit(f"USO_COLETIVO_IDS referencia id(s) inexistente(s): {ids_invalidos}")

    for med in MEDICAMENTOS:
        classificar(med)

    DATA_DIR.mkdir(exist_ok=True)
    out_path = DATA_DIR / "medicamentos.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(MEDICAMENTOS, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"Gerados {len(MEDICAMENTOS)} medicamentos em {out_path}")


if __name__ == "__main__":
    main()
